name: Build and Test

on:
  push:
    branches:
      - Prashu
      - main
  pull_request:
    branches:
      - Prashu

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup a JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build
        run: mvn clean package
      - name: Test
        run: |
          echo running test
          mvn test
    
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup a JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build
        run: mvn clean package
      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.PRASHU_USERNAME}}
          password: ${{secrets.PRASHU_PASSWORD}}
      - name: echo sensitive
        run: |
          echo ${{secrets.PRASHU_USERNAME}}
          echo ${{secrets.PRASHU_PASSWORD}} 
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: prashudocker01/wiprodemo:1.1.0
